#!/bin/bash

export source_directory="${BASH_SOURCE[0]%check-log-quality}"
if [[ "$source_directory" == "" ]]; then
    source_directory='./'
fi

source "${source_directory}/lib/utils.sh"
source "${source_directory}/lib/functions.sh"

initialise_variables
process_command_arguments "$@"
retval=$?

all_files=$(list_files_from_find)

iterate_through_targets "${all_files[@]}"
merge_output_files
